// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCu69nW73b2kBkmLuQ6r8rFfj92_hiBabc',
    appId: '1:416255354969:web:3a4a707bf8d7c4b4432948',
    messagingSenderId: '416255354969',
    projectId: 'oy-dashboard',
    authDomain: 'oy-dashboard.firebaseapp.com',
    storageBucket: 'oy-dashboard.firebasestorage.app',
    measurementId: 'G-GDEPHVHCHH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsvBlpFJDrZaNtvk76JUcF0AXppByIWc0',
    appId: '1:416255354969:android:e7da39c734242dde432948',
    messagingSenderId: '416255354969',
    projectId: 'oy-dashboard',
    storageBucket: 'oy-dashboard.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC348_rzblGazjYE7forQaPpbm_jF88UHc',
    appId: '1:416255354969:ios:0f6fb67f095ab9c0432948',
    messagingSenderId: '416255354969',
    projectId: 'oy-dashboard',
    storageBucket: 'oy-dashboard.firebasestorage.app',
    iosBundleId: 'com.example.oySite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC348_rzblGazjYE7forQaPpbm_jF88UHc',
    appId: '1:416255354969:ios:0f6fb67f095ab9c0432948',
    messagingSenderId: '416255354969',
    projectId: 'oy-dashboard',
    storageBucket: 'oy-dashboard.firebasestorage.app',
    iosBundleId: 'com.example.oySite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCu69nW73b2kBkmLuQ6r8rFfj92_hiBabc',
    appId: '1:416255354969:web:7715eb7751ddf30b432948',
    messagingSenderId: '416255354969',
    projectId: 'oy-dashboard',
    authDomain: 'oy-dashboard.firebaseapp.com',
    storageBucket: 'oy-dashboard.firebasestorage.app',
    measurementId: 'G-K4EQWK94H5',
  );
}
